### ISSUE TITLE
Reminders do not work

### ISSUE THREAD

**Issue by rusty-snake** [quillpad/quillpad#109]
Quillpad: 1.4.6 (F-Droid)
Android: GrapheneOS (AOSP 13)

#### Description

Reminders do not work at all. Likely due to Android 13 notification permission, for quillpad it is greyed out and can not be enabled.

#### STR

1. Create new note and give it a title
2. Set Reminder for it one minute
3. Close app

#### Expected Behaviour

Get Notification as with Quillnote.

#### Actually Behaviour

Nothing.

**Comment by wavy0060** [comment]
I'm having the same issue on Graphene OS.
