### ISSUE TITLE
Lists order is not preserved after an item is checked off

### ISSUE THREAD

**Issue by KenYF** [quillpad/quillpad#110]
Quillpad: 1.4.6 (F-Droid)
Android: Samsung OneUI 4.1, Android 12

Description:
Lists do not preserve sort order when items are rearranged from initial order and an item is checked off. 

Steps to repeat:
1. Create a list with four items [A,B,C,D]
2. Swap B and C [A,C,B,D]
3. Check the checkbox for D
4. Exit the list
5. Reopen the list

Expected Behaviour:
When reopened, list will preserve rearranged order [A,C,B,D], with D crossed out. 

Actual Behaviour:
List resorts to initial order [A,B,C,D].

Extra information:
This bug does not occur if the first item is moved (e.g., [A,B,C,D] to [B,A,C,D]).

Possibly related bug: if an item is created, moved, checked, then unchecked, it returns to its created position instead of its moved position, and the list is resorted to its initial order

**Comment by into-the-v0id** [comment]
See also #159
