### ISSUE TITLE
Non-compliant line spacing in view mode

### ISSUE THREAD

**Issue by serrq** [quillpad/quillpad#135]
When I write a text and I leave two lines spacing empty among lines these are compliant in editing mode but not in view mode.

![1000007546](https://user-images.githubusercontent.com/113377431/231377300-e33f2206-fab2-45c9-b716-b25538dc8a2a.jpg)

![1000007548](https://user-images.githubusercontent.com/113377431/231377340-bc36eb35-3eb1-4926-bd43-c62ae8fe018d.jpg)

**Comment by EphemeralDev** [comment]
I think this is the same as #114, correct me if i'm misunderstanding.

According to jsixface this is part of markdown, [empty lines are collapsed](https://github.com/quillpad/quillpad/issues/114#issuecomment-1485187473)
