### ISSUE TITLE
Sync happening too often

### ISSUE THREAD

**Issue by Asherathe** [quillpad/quillpad#137]
With sync enabled, every time the main screen is loaded, the app syncs, regardless of when it last synced and whether anything has changed. If I open multiple notes to read them  without making changes, it will be syncing constantly, for no reason. I think there should either be some options controling this, or the app should be more intelligent about when it chooses to sync.

**Comment by jsixface** [comment]
I know exactly what you're talking about. That's in my mind too. I'll be fixing this relatively soon.
