### ISSUE TITLE
Can't sync with my own nextcloud

### ISSUE THREAD

**Issue by Kenarso** [quillpad/quillpad#138]
I use nextcloud with a self signed certificate ob my own Server at Home. When I enter and confirm my credentials I get the error message:
"A problem has occurred".
I suspect that it is related to the certificate.

**Comment by jsixface** [comment]
That's likely it. You need to install the self signed certificate as trusted in your phone. 
It's easier to get a certificate from Let'sEncrypt

**Comment by Kenarso** [comment]
IT IS Not so easy wir Lets encrypt, because Inisr an dynDNS ny AVM Fritz. And that ist thebcause why Incan usw let' s encrypt.

**Comment by jsixface** [comment]
Okay. Then I don't think the app can fix your problem. 
The only solution I can think of is to install the self signed certificate. 

https://android.stackexchange.com/a/238859

**Comment by idle-meerkat** [comment]
why plain http is not allowed?(
