### ISSUE TITLE
support markdown header

### ISSUE THREAD

**Issue by agdamsbo** [quillpad/quillpad#141]
Hi. I have Bern very happy to find this app and find it very nice. I am migrating from iOS an Mac towards self hosting. 

I have exported my iCloud notes with a markdown header to save original metadata. Do you plan on supporting this when viewing notes?

Screenshot of edit:
![Screenshot_20230418-104344_Quillpad](https://user-images.githubusercontent.com/43278243/232724109-e184947a-db3d-4798-a397-30ef709e87f1.png)

Screenshot of viewing:
![Screenshot_20230418-104806_Quillpad](https://user-images.githubusercontent.com/43278243/232724426-ad82efaf-82f2-4568-9c41-62f7175cc241.png)

Thanks!

**Comment by EphemeralDev** [comment]
My understanding is that front matter / metadata isn't a part of the commonmark spec, it is an extension of commonmark. I don't believe the markdown library used by quillpad supports this;  I think it would require a patch/upstream support or changing libraries. That being said I would also like to see support for metadata at some point. 

For reference, it seems like there's a few options according to this [stackoverflow answer](https://stackoverflow.com/questions/44215896/markdown-metadata-format/44222826#44222826). It seems like from your screenshots your notes use YAML metadata, [obsidian also uses this format](https://help.obsidian.md/Editing+and+formatting/Metadata).

**Comment by agdamsbo** [comment]
I got an answer, which is now deleted I think. Anyway, I had the option to reexport without the YAML headers. Awaiting version 1.5 with local file sync.
