### ISSUE TITLE
[Issue] Checklist Doesn't Stay Organized

### ISSUE THREAD

**Issue by Privacy-Now** [quillpad/quillpad#159]
Quillpad V1.4.9
Two Pixel 5's always up-to-date
Issue has been around for a few months

When using a checklist I'll organize my items, say between groceries and non-grocery items. The items will sometimes revert back to their original position upon creation order or sometimes I believe they just go down one item. The former way is much more common, nearly every time I create a decent length list (10+ about). The former happens when I back out of the note wether to the Quillpad home or exit the app completely. The latter issue tends to happen when I check and uncheck an item a few times.

**Comment by G-i-o** [comment]
QP v.1.4.10
Lineage 20 (Android 13).

Having the same issue as above.

In addition to the above, I noticed:
- When adding an item to the list, the item gets pushed out of order to the end of the list.
- When moving an item from one position to the other, it frequently goes back to the original position, especially when exiting and re-entering the edit mode.

Thank You for your support and to @privacy-now for having reported this. :pray:

**Comment by nWestie** [comment]
I am also noticing this issue frequently:
Android 11, Quillpad 1.4.10

Same issues:
- items added in the middle move to the end when I start typing
- when dragging items, they will return to their original positions when I close the note
-
