### ISSUE TITLE
Nextcloud sync - can't connect

### ISSUE THREAD

**Issue by mortenee** [quillpad/quillpad#166]
I'm using Hetzner Storage Share for nextcloud. When trying to connect with the same url and credentials i've previously used with Joplin I get a message saying "something went wrong", and can get no further.
Is there somewhere I can look for a more detailed error message? 
And has anybody else succeeded in connecting to nextcloud hosted by Hetzner?

**Comment by jsixface** [comment]
Quillpad specifically connects to the Notes app inside nextcloud.  Do you know if the Notes API is exposed in your server ?

**Comment by mortenee** [comment]
Probably not... Hadn't seen that was necessary. Is that documented somewhere that I should have seen?
Will check/fix the Notes API on the server and test again :)

**Comment by mortenee** [comment]
Enabled notes and it works now :)
