### ISSUE TITLE
Feature: very reduced notes listing option

### ISSUE THREAD

**Issue by OlliZabal** [quillpad/quillpad#174]
I guess it would be great to have another list overview option as a very reduced listing showing f.e. only the notes titles.

**Comment by nofishonfriday** [comment]
If I don't misunderstand, this is possible since v1.4.10.
check the demo video:
https://github.com/quillpad/quillpad/pull/153

**Comment by OlliZabal** [comment]
@nofishonfriday you understood correctly. I didn't see that option for each note. That's exaclty what I meant. Great would be a general option to change that for all notes in the main settings of the app (f.e. for users having many notes).

**Comment by nofishonfriday** [comment]
It's also possible to do it for all existing notes at once.
Check demo:
https://github.com/quillpad/quillpad/pull/161

(Though new notes will appear with full preview.
An option to have new notes appear with full or compact preview by default would be nice but is miissing currently.)

**Comment by jsixface** [comment]
F-droid takes a couple of days to pick it up from the release page.
