### ISSUE TITLE
List doesn't show checkboxes with default font size on latest version

### ISSUE THREAD

**Issue by Desidiosus** [quillpad/quillpad#232]
Noticed a regression with the latest version (1.4.12) that the list notes didn't show checkboxes with the default font size. Also adding new items to the list didn't get saved as converting the list to a note removed the items I added. 

The workaround was to set the font size to anything other than default (15 seems to be closest to the default). After that everything works as expected.

**Comment by lazerleif** [comment]
Same here! Thanks for the workaround
