### ISSUE TITLE
Problems with checklist

### ISSUE THREAD

**Issue by lazerleif** [quillpad/quillpad#235]
Having some strange problems with checklists. Items disapears when i go back and items disapears when i removd tasks. See attached video. 

Edit: Problem started on 1.4.12 and remained on 1.4.13

https://github.com/quillpad/quillpad/assets/37516628/ae413d8c-fe66-432b-a35e-48ba02c588a6

**Comment by lazerleif** [comment]
This only occurs when "Move (un)checked items on the list" is set to "No"

**Comment by tetris4** [comment]
I don't know if it's the same problem, but together with this, on my system the checkboxes have also disappeared.

The workaround by @lazerleif fixes the issue above but not mine. I can't even check something as done.

https://github.com/quillpad/quillpad/assets/1158465/6a98cff0-0a4f-4ce6-9a43-696c7cc0f03d

**Comment by lazerleif** [comment]
> I don't know if it's the same problem, but together with this, on my system the checkboxes have also disappeared.
> 
> The workaround by @lazerleif fixes the issue above but not mine. I can't even check something as done.
> 
> Running F-Droid version 1.4.12 on Android 14 on a Samsung device.
> Screen_Recording_20240220_234011_Quillpad.mp4

There is a workaround for that too. Change font size to 15. Settings -> Text editor/view font size. 
Credit to @Desidiosus, https://github.com/quillpad/quillpad/issues/232#issue-2139922380

**Comment by reinhard-weber** [comment]
Still present on v1.4.13

**Comment by lazerleif** [comment]
> Still present on v1.4.13

I was referring to the problems with disappearing checkboxes 🙂

**Comment by nofishonfriday** [comment]
This looks like what I reported [here](https://github.com/quillpad/quillpad/pull/165#issuecomment-1861877246).
There's actually a (intended) fix for it already submitted for v1.4.12 (https://github.com/quillpad/quillpad/commit/547a3e4543843df6aaf96da70cb58c57982bd853) but I can confirm it still happening with v1.4.12 (v1.4.13 is not yet available on F-Droid, but I see no additional commits adressing it.)
