### ISSUE TITLE
Convert To List Feature Bug

### ISSUE THREAD

**Issue by rvyhvn** [quillpad/quillpad#254]
Everytime I convert from markdown to list for task, it does'nt save the list. All of my assigned task in the list are gone.

Edit: currently I'm on version 1.4.13

**Comment by njmdietrich** [comment]
Yes. I have been facing the same issue. It must have been introduced either in 1.4.12 or 1.4.13

**Comment by nofishonfriday** [comment]
I think this should be [fixed](https://github.com/quillpad/quillpad/commit/79a4442016831a50b217e8bf292dd31e9d11ce7f) already for 1.4.14 (not released yet).

**Comment by rvyhvn** [comment]
> I think this should be [fixed](https://github.com/quillpad/quillpad/commit/79a4442016831a50b217e8bf292dd31e9d11ce7f) already for 1.4.14 (not released yet). 

Okay, thanks!

**Comment by nofishonfriday** [comment]
I said *I think*. :)
If not fixed in 1.4.14 feel free to reopen the issue.

**Comment by rvyhvn** [comment]
> I said *I think*. :)
> If not fixed in 1.4.14 feel free to reopen the issue. 

Sure. The matter is I know there are bug fixing going on. Currently I'm just waiting the next version to be released.
