### ISSUE TITLE
Items are not saved in a list

### ISSUE THREAD

**Issue by BoneNStone** [quillpad/quillpad#256]
After i close the list note all the items disappear from it. When opening again i have an empty list, however the number of lines is preserved.

**Comment by ballessay** [comment]
I can confirm the behavior, too. 
Checked the new commits in the current release v1.4.13. It looks like the problem and current work around are in [issue #235.](https://github.com/quillpad/quillpad/issues/235#issuecomment-1969690112)

> I toggled the setting for checklist: Move (un)checked items in the list and swtiched it to yes and the issue was resolved for now. 

I can confirm. Setting the option to yes and the checkbox text get saved as expected.

HTH

Thanks for this helpfull application.

**Comment by BoneNStone** [comment]
@ballessay, Thanks for the tip. However as you mentioned it is a work around, not a solution. And since that issue is closed i think will keep this one open.

**Comment by ballessay** [comment]
@BoneNStone no problem. I don't like that the positions change but I can live for it atm.  

After writing the comment I had closer look on that issue and the referenced commits. I just want to point out:

The last/current release was 2024-02-18
The potential fix seems to be in (https://github.com/quillpad/quillpad/commit/79a4442016831a50b217e8bf292dd31e9d11ce7f](commit) from 2024-03-01.

So I guess in the next release the behavior should be back to normal.

But maybe a person related to this project may or may not confirm this. I'm just a simple user here.  ;)

**Comment by nofishonfriday** [comment]
> The potential fix seems to be in [commit](https://github.com/quillpad/quillpad/commit/79a4442016831a50b217e8bf292dd31e9d11ce7f) from 2024-03-01.

> So I guess in the next release the behavior should be back to normal.

Yes, that's what I'm expecting/hoping (as the fix comes from me). :)
