### ISSUE TITLE
Tapping on camera icon crashes app

### ISSUE THREAD

**Issue by laraib07** [quillpad/quillpad#28]
Whenever I tap camera icon on the bottom to add an image, the app crashed.

**Comment by jsixface** [comment]
What version of the app are you running ?
Built from master branch or APK from releases /Google play ?

**Comment by laraib07** [comment]
Apk from releases, and I faced this issue on quillnote too.

**Comment by fischer-felix** [comment]
Can your try to install tasks.org from Google play or f droid and try to take an image from an task (add attachment).

If this also does not work, there might be a problem with the camera of Arrowos

**Comment by laraib07** [comment]
@fischer-felix Thanks, I figured out the issue. I followed your instructions and found out the problem was on my phone. I disabled stock camera (gcam) as it was buggy. I am using graphene OS camera for all intents and purposes. 
Whenever I tapped camera icon, it triggered the stock camera and failed.


I think the app should give user choices to which camera app to use in case user have multiple camera apps.
