### ISSUE TITLE
Inserting CR/LFs via <br/> doesn't work

### ISSUE THREAD

**Issue by cmvizitiu** [quillpad/quillpad#299]
1.4.15 (F-Droid); Android 12 

Attempting to push down a `H` by adding multiple `<br/>` leaves the extra CR/LFs collapsed. E.g. instead of 
\
An example, space before and after `H`
<br/><br/><br/>
## Header
<br/><br/><br/>
... a text like this:
```
An example, space before and after `H`
<br/><br/><br/>
## Header
<br/><br/><br/>
```
... gets rendered as
\
An example, space before and after `H`

**Comment by nofishonfriday** [comment]
`<br/>` is a HTML tag, not sure markdown editors are _required_ to support it? (most seem to do though).
Anyway, as alternative, in markdown mode you can use &nbsp; to insert empty line, or disable markdown mode, then the empty lines entered via keyboard are kept.
