### ISSUE TITLE
Consistency in selecting single and multiple notes - UX improvement

### ISSUE THREAD

**Issue by laraib07** [quillpad/quillpad#30]
Selecting a single note prompt bottom drawer with option to select more. 
![Screenshot_20221125-230637](https://user-images.githubusercontent.com/25507825/204036165-7f9b8f81-6cf6-4902-9c6d-0a5eec14e650.png)

When you select "Select more..", you can select multiple notes and to get similar options as bottom drawer you have to press overflow menu button. 

![Screenshot_20221125-230651](https://user-images.githubusercontent.com/25507825/204036128-aaa02602-f7df-4996-9e47-5bde217128ec.png)

I think, for consistency, you can remove bottom drawer as it doesn't serve any purpose. You can do everything with single overflow menu. 
Also, more than often I accidentally tapped on options given in suddenly popped bottom drawer whenever I select any notes (and intend to select more).

**Comment by jsixface** [comment]
The most used options for most users are delete, pin and hide on a single note. The bottom drawer menu sits closer to the thumb and it's easier to access. Removing that menu would entail that users have to select a note by holding down, then reach for the three dots on the top and access the menu that's relatively higher. This is not a better alternative for this use case. 

If the use case is to select multiple notes, the only way your suggestion help is removing the need to choose "Select more..." which is convenient near the thumb.

**Comment by laraib07** [comment]
Valid points!
