### ISSUE TITLE
Material You colors don't look correct in light mode

### ISSUE THREAD

**Issue by githubcatw** [quillpad/quillpad#301]
The fix introduced in 1.4.15 doesn't seem to be enough - while the note list looks correct, notes still use dark text on a dark background:
![Screenshot_20240427-231505.png](https://github.com/quillpad/quillpad/assets/17374742/870f1a0f-e4fe-4a66-b475-67f4273634ac)

This is also true for the previews in the note list:
![Screenshot_20240427-231501.png](https://github.com/quillpad/quillpad/assets/17374742/bf0919ec-35d8-4c1f-b600-da3152ece9b9)

I'm using Android 15 beta 1.1 on a Pixel 6, but this also happened in Android 14.

**Comment by shamy38** [comment]
same issue here on Pixel 6a.
cc @DreamyLynn
