### ISSUE TITLE
Links in dark mode are invisible when Material You colors are enabled

### ISSUE THREAD

**Issue by githubcatw** [quillpad/quillpad#307]
## Steps to reproduce 
1. Enable the Material You theme and put the device in dark mode.
2. Make a new note and write: `I take notes using [Quillpad](https://github.com/quillpad/quillpad), an open-source app.`
3. Save the note.

**What should happen** - the entire message is shown:
> I take notes using [Quillpad](https://github.com/quillpad/quillpad), an open-source app.

**What happened** - the link text is invisible:
> I take notes using                   , an open-source app.

## Screenshots
![](https://github.com/quillpad/quillpad/assets/17374742/214f7e97-a0e8-4991-a227-704c0085b56d)

## Environment
I'm using a Pixel 6 with Android 15 beta 2 and Quillpad 1.4.15.

## Notes
While light mode colors are incorrect - see #301 - this issue doesn't apply to it:

![](https://github.com/quillpad/quillpad/assets/17374742/9df79bb4-916f-46e2-8137-faa1690f6f5e)

**Comment by mewtant** [comment]
Same experience. I have “Theme mode” set to “Follow system” (dark), “Dark theme mode” set to “Standard,” and “Color scheme” set to “Follow system” (Material You on Android 12). I can’t see URLs in view mode ***or the cursor in edit mode***. I can see them, just barely, if I change “Dark theme mode” to “Black,” and they show up pretty well if I change a note color to pink.

But in other respects a very useful app! Thanks!
