### ISSUE TITLE
WebDAV

### ISSUE THREAD

**Issue by opk12** [quillpad/quillpad#308]
What about adding support for WebDAV? It is standard, and very easy to self-host at home. Has lightweight server implementations, even Apache and nginx support it natively, and it's just a matter of writing the config file. PHP + Nextcloud is the opposite of all that.

Using a standard protocol also future-proofs the app, which is now tied to NextCloud staying alive and not breaking its own API.

**Comment by opk12** [comment]
Duplicate of #124

**Comment by tangshg** [comment]
![image](https://github.com/quillpad/quillpad/assets/37105296/befdcddf-22b7-4c24-a78f-abfb4723ef04)
I am adding the webdav service and my work is very busy. I have very little time, so it will take some more time
