### ISSUE TITLE
Remove DependencyInfoBlock for F-Droid

### ISSUE THREAD

**Issue by linsui** [quillpad/quillpad#363]
We find that there is a `DependencyInfoBlock` in your APK.

It's a [Signing block](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367) and [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056).

While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**Comment by jsixface** [comment]
@linsui If I set these two options to false, will it affect the build for Google Play store?

**Comment by linsui** [comment]
I don't think so. And IIUC you upload aab to google play so you can disable it for apk and aab won't be affected.

**Comment by jsixface** [comment]
Published the changes

**Comment by linsui** [comment]
Thanks!
