### ISSUE TITLE
Add list entry when pressing enter

### ISSUE THREAD

**Issue by jsixface** [quillpad/quillpad#39]
If currently adding a list, add a ` -` automatically when pressing enter to go the next line.

When enter is pressed again without typing anything, remove the added list prefix and make that a normal line.

**Comment by bagajohny** [comment]
Is it possible to do this for numbered list also?

**Comment by jsixface** [comment]
It's a bit tricky to implement. But yes.

**Comment by bagajohny** [comment]
I request you please implement it. The convenience level will increase exponentially.

**Comment by TheHawaiianKoala** [comment]
Kindly also implement this for markdown tasks aswell i.e. - []

**Comment by TheHawaiianKoala** [comment]
Hello, tested 1.4.5 but the list doesn't automatically add - or number or check list

**Comment by jsixface** [comment]
Oh yeah. 
It was working with the actual keyboard.

It's not working with the Android keyboard. I'll check
