### ISSUE TITLE
Additional delete objects in bin option

### ISSUE THREAD

**Issue by ctntt** [quillpad/quillpad#40]
As an enhancement one could add a 'Never' option to 'Delete notes in bin' so you can keep your notes in the bin as long as you want.

**Comment by jsixface** [comment]
How is this different from keeping the notes out of sight in a different "Notebook".

**Comment by ctntt** [comment]
As mentioned it is just a possible (not necessary) enhancement because it is the behavior I expect from a recycle bin (that it doesn't clears itself). 

There is already the '30 days' option which should be enough in most use cases.
