### ISSUE TITLE
Compact notes list

### ISSUE THREAD

**Issue by smaragdus** [quillpad/quillpad#42]
@jsixface 

First, thanks for maintaining and developing this project.

I would like to suggest a simple enhancement- a new option in settings for showing only notes titles in notes list, without showing part of the notes text and notes tags. I mean something like that:

![Screenshot_20221130-164146](https://user-images.githubusercontent.com/9025757/204848709-74a7266e-65e0-4d23-9c21-fd0887f48a69.png)

I prefer a compact notes list as shown in the screenshot above. With an option for compact notes list (only notes titles shown) there would be less scrolling when the notes list grows bigger.

Regards

**Comment by landry314** [comment]
I second this. I don't need to see the beginning of a note before opening it. It just makes an unnecessary long list of notes. Adding a setting to the layout setting would be nice. "Grid, List, Compact"

**Comment by smaragdus** [comment]
Thanks for version [1.4.10](https://github.com/quillpad/quillpad/releases/tag/v1.4.10 ), now the app looks better for me and the note list is slimmer and easier to manage. My only complaint is that **Compact preview** option is per note, not global, so I have to activate it for any new note created.

I would be glad if there is an option for global **Compact preview** option for every new note created.

**Comment by landry314** [comment]
i totally agree. i love the feature but i would love a global setting as i posted above! "Grid, List, Compact". you could still allow manual override for each note separately.

**Comment by smaragdus** [comment]
I suppose the easiest solution would be a new option in settings:

- Preview mode
  - Compact preview
  - Full preview
 
Thus the user would not need to activate **Compact preview** for every single new note created.
