### ISSUE TITLE
Tags sorting

### ISSUE THREAD

**Issue by smaragdus** [quillpad/quillpad#44]
@jsixface 

I would like to suggest a new option in settings- sorting of tags in alphabetical order. Now tags are not sorted which means that when there are many tags the tags list becomes a mess. This may be implemented in two ways:

- automatic sorting of tags in alphabetical order;
- manual sorting of tags in alphabetical order;

Either way would be fine for me- I need an option for sorting tags alphabetically so that I would be able to find the needed tag easily.

Regards

**Comment by jsixface** [comment]
Yeah I think sorting alphabetically or recently added is a good option to have. 

I was also thinking of automatically creating tags when you add a hashtag in the notes. Like #recipes #travel.

**Comment by groaking** [comment]
I would love to have tag sorting in **Quillpad**, too!

It's been two years. Is there any progress on this issue?
