### ISSUE TITLE
New app logo

### ISSUE THREAD

**Issue by jsixface** [quillpad/quillpad#45]
We need a new version of app logo preferably similar to the original Quillnote icon. This will differentiate the app in the Google play and F-Droid app stores from Quillnote.

A newer base color instead of blue is also welcome. 

Need:
 - Logo
 - App icon
 - Store banner with the new logo

**Comment by fischer-felix** [comment]
Like this maybe?

![icon](https://user-images.githubusercontent.com/65448408/204902971-010c7208-ea3e-4986-ba94-f81f2dc2adca.svg)

**Comment by jsixface** [comment]
Thanks. I was thinking a little vibrant color and it looks more like a quill and less like a leaf. I always got the leaf vibe from the Quillnote logo. [Sample pic](https://www.kindpng.com/picc/m/43-435160_feather-quill-pen-transparent-background-hd-png-download.png)

Sidenote: If you're using something like photoshop or illustrator, do you mind creating a `graphics` folder in the repo and put it there; create a PR. This will be helpful in the future if we decide to tweak a bit.

**Comment by fischer-felix** [comment]
Sure, will take that into consideration. 👍
I'm using Inkscape, for the design, should I still make a graphics folder?

**Comment by jsixface** [comment]
Yes. If you're okay with making that open source.

**Comment by bagajohny** [comment]
I would like to suggest a shade of green colour in place of current blue colour. 

<img src="https://i.pinimg.com/originals/4d/ed/d0/4dedd0675d42aba8673d6afa3cf5923a.png" width=50% height=50%>



> I always got the leaf vibe from the Quillnote logo. Sample pic

Yes leaf is the way to go.

**Comment by EphemeralDev** [comment]
I was thinking a green as well, sort of like the green/blue [parakeet](https://en.wikipedia.org/wiki/Parakeet) colors. Personally i like the first 3 greens in your palette. I didn't really make the connection to a leaf but i see it now and that might not be desirable. As for the logo I was thinking maybe a capital Q, with the feather being the bottom line of the Q or maybe a quill resting on a notepad (maybe too generic?)?

**Comment by jsixface** [comment]
That's a fantastic idea. I really like the Q and a feather for the short line. I also like the first and the third colors in the palette.

**Comment by bagajohny** [comment]
Q also sounds good idea.

How about this shade?
https://encycolorpedia.com/b6d72c

**Comment by fischer-felix** [comment]
![drawing](https://user-images.githubusercontent.com/65448408/205465495-ad853967-e834-49a1-9940-0ec4ff894f74.svg)
Like this (https://github.com/fischer-felix/quillpad/tree/new-app-logo)?

**Comment by jsixface** [comment]
I like it very much. 

Can we flip the direction of the feather and have some strands Of hair near the tip. Here's my amateur effort:
![image](https://user-images.githubusercontent.com/2518805/205474108-f7dfb0cb-ea8e-4382-8c46-344f3b305278.png)

**Comment by fischer-felix** [comment]
![drawing](https://user-images.githubusercontent.com/65448408/205499894-b7a22cda-6910-40ff-b1d8-9589b3561cb5.svg)

might need to make the feather a bit smaller, what do you think?

**Comment by jsixface** [comment]
Yes. It has to be a little bit smaller.
We'll also have to see how it looks within the size of an icon.

**Comment by bagajohny** [comment]
I had the opposite thing in mind. Means the background would be green and the logo would be white. Similar to current Quillnote logo.

**Comment by fischer-felix** [comment]
Tried them on my phone and the emulator.
If we end up going white on green, we might have to use a different shade, because like this there is not quite enough contrast.

Should I create a PR for this, or should we keep the discussion in this issue?

![Screenshot_20221204_184137](https://user-images.githubusercontent.com/65448408/205507341-419e919d-05d7-47a4-b185-62df04d4273e.png) | ![Screenshot_20221204_184539](https://user-images.githubusercontent.com/65448408/205507347-7e2f77ff-7e04-451e-afca-5183ddcb35d1.png)
--- | ---
![Screenshot_20221204_184102](https://user-images.githubusercontent.com/65448408/205507365-083ad4ea-91bd-4da5-9cfe-5eb9e199ca11.png) | ![Screenshot_20221204_184529](https://user-images.githubusercontent.com/65448408/205507367-f689c5ba-f191-48fe-adcc-f84cba62f779.png)
![Screenshot_20221204_184037](https://user-images.githubusercontent.com/65448408/205507446-bf31eaa8-4fad-4086-9085-1b3ff5cd427e.png) |

**Comment by EphemeralDev** [comment]
I never made the distinction before but according to the [Google Play spec](https://developer.android.com/distribute/google-play/resources/icon-design-specifications), the launcher icon and the google play icon are  (or can be) different. So maybe the green icon can be the 'brand'/play store icon, and a monochrome/material you icon can be the launcher icon.

**Comment by NeNpO** [comment]
Great job guys! The new logo is amazing.



> I never made the distinction before but according to the [Google Play spec](https://developer.android.com/distribute/google-play/resources/icon-design-specifications), the launcher icon and the google play icon are (or can be) different. So maybe the green icon can be the 'brand'/play store icon, and a monochrome/material you icon can be the launcher icon.

I Send that! Perfect idea.



> I like it very much.
> 
> Can we flip the direction of the feather and have some strands Of hair near the tip. Here's my amateur effort: ![image](https://user-images.githubusercontent.com/2518805/205474108-f7dfb0cb-ea8e-4382-8c46-344f3b305278.png)

I think that the quill is better with the tip pointing down. It gives the sensation that it's writing. Like a hand holding the quill ready to start writing.

What do you think?

**Comment by fischer-felix** [comment]
That was my original idea as well, but now I like it either way.

**Comment by jsixface** [comment]
Most common pictures of quills I've see are set pointing to bottom left. So I'm not very particular on which way it points, I'm okay with either way. 

As for the colours, I like the dark background and green Q for regular icons and the lighter Q for the Material You icons. We can use the green icon with the white background for branding / website and README. 

We can continue the discussion here, if any more needed. When creating the PR, can you have the source material (inkscape files) in the `graphics/` directory and then replace the existing icons with the new ones ?

**Comment by KLaurence** [comment]
I think there was an oversight with the usage of Android Green. Quillnote/Quillpad has two in-app Green colors (for the color-scheme settings), `#c5e1a5` for light and `#38573a` for dark.

![Comparison for Quillpad greens](https://user-images.githubusercontent.com/6565795/206701136-68888316-fb4e-474b-b50e-26b583c7114d.jpg)

Should the logo's green also be the app green (probably the light green)? If yes, should the app's default color-scheme also be Green? (It's currently Blue, which is `#81d4fa` for light and `#273749` for dark.)

**Comment by jsixface** [comment]
Closing this issue since we have the primary icon, logo and the banner. 
Rest of the theming is being mentioned in the other issues to be solved
