### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by jsixface** [quillpad/quillpad#5]
Get the app and included in the F-Droid repo and made available for installation through f-droid.

**Comment by jsixface** [comment]
App request [merged](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12116) to the main F-Droid repo. Waiting for the app to show up in the search.

**Comment by jsixface** [comment]
Publishing is blocked in F-droid due to a [signing server issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2816#note_1186499885).

**Comment by shuvashish76** [comment]
Live on F-Droid : https://f-droid.org/packages/io.github.quillpad/ 🎉
