### ISSUE TITLE
Google Play store release

### ISSUE THREAD

**Issue by jsixface** [quillpad/quillpad#6]
Release the app in google play store.

**Comment by jsixface** [comment]
Woohoo. The app is now published in Google play store. [Here's the link](https://play.google.com/store/apps/details?id=io.github.quillpad)

**Comment by fischer-felix** [comment]
Maybe there should be something on there about the fact that this is the "successor" so to speak to Quillnote.

**Comment by jsixface** [comment]
Yeah. I'll include that in the next release.
