### ISSUE TITLE
Features request - multiple

### ISSUE THREAD

**Issue by sconim** [quillpad/quillpad#68]
Hi,

I'm really ecstatic to see a fork of QuillNote being worked on. The app has phenomenal potential and I can't wait for it to see it growing - thank you guys!

While I've read your notes and the planned roadmap, please consider the feature suggestion list below which was originally posted on QuillNote's GitHub page.

1. Implement **font** size options (larger).
2. Improve **search** capability, where (a) the number of found matches is indicated, (b) found matches are highlighted in text, and (c) they are scrollable across all matching notes.
3. **Automatic bullet & numbering** lists (apply bullet formatting or numbering to all selected text, as well as when jumping to a new row - similar to Enter on keyboard in a Word document).
4. Option in settin**gs to no longer jump to the end** of note when editing, but rather keep the cursor at current indexing location (very annoying in large notes to have to come back and search AGAIN, for location intended to be edited).
5. Allow notebooks to be manually (alphabetical) **re-sorted in left menu** as well as in settings.
6. Implement selective **encryption**, or at least password / biometric protection to allow for each note to be protected independently.
7. Add a **condensed quick view mode** to allow as many notes as possible to be viewed at a glance.
8. Add option in settings for app **start-up screen**: (1) All Notebooks - overview showing all created notebooks, (2) Specific Notebook, or (3) All notes (current view).

Thanks a lot!

**Comment by jsixface** [comment]
Hello. Thanks for the detailed list. Since it is difficult to track multiple issues in a same ticket, can you create individual ones ?  I also see some duplicates - for example - the automatic bullets (3) and the condensed view mode (7) are already listed in the existing tickets.

**Comment by sconim** [comment]
Sure, I'll do that!

Best,
Cosmin

**Comment by sconim** [comment]
Done! 😁
