### ISSUE TITLE
In edit mode, the button to go back to view mode covers the note.

### ISSUE THREAD

**Issue by magnus-ISU** [quillpad/quillpad#83]
Put it in the toolbar instead?

Or autmatically scroll down when typing at the bottom.

**Comment by nofishonfriday** [comment]
@jsixface Isuue could maybe be closed with the merging of #134? :)

**Comment by magnus-ISU** [comment]
Hmm. I have it installed from Fdroid and didn't get that update. I'll close it assuming it is done, but why is fdroid not updated?

**Comment by magnus-ISU** [comment]
Oh nevermind. It is still not in 1.4.9 I guess, but will be in the next version.

**Comment by jsixface** [comment]
Yes it'll be in the next version. 

Can you get the APK from this build and test it?
https://github.com/quillpad/quillpad/actions/runs/4903097523/jobs/8755335768
